### Post kindle file
POST http://localhost:3002/upload/kindle-file/e7a4d691-e977-46b6-ba81-ec5738a0c7dd
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlN2E0ZDY5MS1lOTc3LTQ2YjYtYmE4MS1lYzU3MzhhMGM3ZGQiLCJ1c2VyRW1haWwiOiJ6dXppYTEyM0BnbWFpbC5jb20iLCJpYXQiOjE3MzkzNzUyODQsImV4cCI6MTczOTM3ODg4NCwiYXVkIjoibG9jYWxob3N0OjMwMDIiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMiJ9.efQrR9CdOIZS_gWq4NhLkZIEc90oQfLHnZwk6FCtbIw
Content-Type: multipart/form-data; boundary=boundary123

--boundary123
Content-Disposition: form-data; name="file"; filename="My Clippings.txt"
Content-Type: text/plain

< C:/Users/ethen/Desktop/My Clippings.txt
--boundary123


### Get user files
GET http://localhost:3002/upload/fetch-user-files/e7a4d691-e977-46b6-ba81-ec5738a0c7dd
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlN2E0ZDY5MS1lOTc3LTQ2YjYtYmE4MS1lYzU3MzhhMGM3ZGQiLCJ1c2VyRW1haWwiOiJ6dXppYTEyM0BnbWFpbC5jb20iLCJpYXQiOjE3MzkzNzUyODQsImV4cCI6MTczOTM3ODg4NCwiYXVkIjoibG9jYWxob3N0OjMwMDIiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMiJ9.efQrR9CdOIZS_gWq4NhLkZIEc90oQfLHnZwk6FCtbIw
